# Generated by Django 3.0.8 on 2020-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preperation_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('LH', 'Lunch'), ('DI', 'Dinner'), ('DE', 'Dessert')], default='DI', max_length=2),
        ),
    ]
