# Generated by Django 3.0.8 on 2020-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
